### ISSUE TITLE
Support Sponsorship

### ISSUE THREAD

**Issue by dsikes** [motla/vue-document-editor#11]
I think this project could be very valuable to me. If you can enable sponsorship, I'd be happy to sponsor some work on this project. 

There are a few features I can think of that I would need, but one of the main features that I would be looking to see is exporting to a Word (.doc or .docx) document. I know this will likely be very challenging.

Another feature that would be very useful, and probably signicantly easier would be variable placeholders, (using a document as a template).

Again, thanks for the awesome project. I'm very interested in seeing it succeed.

**Comment by motla** [comment]
Hi @dsikes, thanks for your message.

Unfortunately I have no more time to work on this, it was last year's summer project. I can support bugs and compatibility issues, but I don't plan to improve it for now, sorry.
The challenge was originally to use `<contenteditable>` and JavaScript to detect fixed-size page overflow and split content over pages. My algorithm works, but has some drawbacks:
- [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) that is used on every button of the toolbar is deprecated and may not be included in further versions of web browsers
- we can't measure the size of text words directly in JavaScript, so to detect page overflows, the algorithm moves DOM elements on every user input, checks if pages overflows and moves back elements. This is clearly a hack and this processing grows with the number of pages, so it is not adapted for large documents. I haven't found an alternative algorithm that uses the native `contenteditable` implementation yet. For this reason I discourage you to use this library as a base for a powerful application accepting large/complex .docx documents. It is more adapted for simple and low number pages such as invoices and contracts.

On the contrary, Google Docs (proprietary Kix algorithm) does not use the native `contenteditable` implementation. Instead it computes every word size and process their position outside HTML DOM to place them at the correct page. This is a totally different development (much complicated), which explains why we can't find free libraries which do this so easily.

For the variable placeholders, you can use template pages as explained in the [API](../API.md) using `{ template: YourComponent, props: { placeholder1: 'My value' } }` and writing `{{placeholder1}}` in the correct position of your Vue.js component `<template>`.
