### ISSUE TITLE
adjust line height of paragraph

### ISSUE THREAD

**Issue by volserverRay** [motla/vue-document-editor#12]
Hi there,
Thanks for creating this awesome package!
I would like to know how do we able to adjust the line height of the paragraph?
Because according to the DEMO, I can't find any clue how to achieve this with the toolbar.
Please advise.

**Comment by motla** [comment]
Hello!
I guess this is not possible directly with using `document.execCommand()`
Instead you'll have to create a short Vue method like:
```javascript
methods: {
  setLineHeight (value_string) {
    const sel = window.getSelection();
    const element = sel.focusNode.tagName ? sel.focusNode : sel.focusNode.parentElement;
    element.style.lineHeight = value_string;
  }
}
```
Then you call this method with a click handler like `click: () => { this.setLineHeight("15px"); }`.

Good luck with that. Let me know if you still have issues.
