### ISSUE TITLE
Enter key to create new line doesn't seem to work on the demo site

### ISSUE THREAD

**Issue by senkwe** [motla/vue-document-editor#2]
**Describe the bug**
Enter key to create new line doesn't seem to work on the demo page

**To Reproduce**

1. Create a New Document
2. Type a short sentence
3. Press the "Enter" key to create a new line
4. Typed text is deleted

**Comment by motla** [comment]
Thanks a lot for reporting this bug.
Probably some recent updates inside web browsers because I'm pretty sure it had worked previously.
I just released commit https://github.com/motla/vue-document-editor/commit/27ede0e9d2e6248a23b2ebc6e56db0ac0af03062 (v1.1.1) that fixes it.
Have a nice day
