### ISSUE TITLE
can we set certain pages to landscape then back to portrait?

### ISSUE THREAD

**Issue by corilin** [motla/vue-document-editor#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by corilin** [comment]
Now we can perfectly to preview the document and print it out as we see, but when the content got wider table columns, the content becomes broken and unclear.  Is there any way to set the page directions?

**Comment by motla** [comment]
Hello!
Unfortunately, this is not possible... I'm sorry. It would require a massive core rewriting if we want to implement it, as the split algorithm can manage only one page size, measured and fixed at initialization.
