### ISSUE TITLE
Issue when editing data with overlay

### ISSUE THREAD

**Issue by guilhermeagirardi** [motla/vue-document-editor#23]
Hello!
I can't edit the page data because the overlay is over the content.

When I click here
![image](https://user-images.githubusercontent.com/2306117/204887844-b6ee684d-bef8-43fe-9188-8360bb04fa0e.png)

If I remove overlay, all works fine. However I need header and footer.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 2.2.1
 - Vue.js version: 3.2.45

**Comment by motla** [comment]
It is weird because the overlay is set with CSS property `pointer-events: none` which should disable the mouse interaction with div.overlay and allow the user to modify the content through the overlay div.
Can you provide me a working example of your app so I can take a look?

**Comment by motla** [comment]
I close the issue as you don't answer. Don't hesitate to reopen it if you still have issues.
