### ISSUE TITLE
Backspace key is broken with one page content

### ISSUE THREAD

**Issue by RuneMolin** [motla/vue-document-editor#24]
**Describe the bug**
Backspace key does not work if content only has one page

**To Reproduce**

Modify Demo.vue,  change content to 

```     
 content: [
        { template: markRaw(InvoiceTemplate), props: { invoice_number: "AB38052985" } },
      ],
```

Now run the demo and try to delete text with backspace key.

**Expected behavior**
Backspace key works in all circumstances.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome, Firefox
 - Version 2.2.1
 - Vue.js version 3.2.45

**Additional context**
This is either caused by  the fix for https://github.com/motla/vue-document-editor/issues/16 or a failure on my part to understand how the component is used.

**Comment by motla** [comment]
Indeed... Sorry for that, and thanks for reporting.
I just released v2.2.2 (Vue3) and v1.4.1 (Vue2), which should correct the bug.
Let me know if you still have issues.
