### ISSUE TITLE
Table Page Break

### ISSUE THREAD

**Issue by amaliaka** [motla/vue-document-editor#28]
I found a problem when I use a table element where the content within a second or subsequent column exceeds the height of the previous column within the same row, it may lead to irregular formatting due to page breaks.
![image](https://github.com/motla/vue-document-editor/assets/16041848/d5507001-cf56-4d84-8f73-da505aa66203)

**Comment by motla** [comment]
Hi @amaliaka 
Thanks for your bug report.
I just released v2.3.0 (Vue3) and v1.5.0 (Vue2) which should workaround your issue.
Now table rows don't split over multiple pages, they just move to the next page if one of its cells make it overflow.
Unfortunately, it is too complicated to code a behavior similar to Microsoft Word (where a row can split over multiple pages) with this implementation...
I hope it will fit your needs.
