### ISSUE TITLE
Syntax Error: Unexpected token (299:56)

### ISSUE THREAD

**Issue by dastanzholdas** [motla/vue-document-editor#38]
"vue": "^2.6.10",
"vue-document-editor": "^1.5.1"

![image](https://github.com/motla/vue-document-editor/assets/115471070/8de9783c-5dd7-4e7a-b09c-01b9c4a638d9)
![image](https://github.com/motla/vue-document-editor/assets/115471070/1b0cf33b-ff90-4dfa-a4bd-8f2410e46b0f)
 In emit_new_content methods

**Comment by motla** [comment]
what compiler are you using? can you share your package.json file?

**Comment by VoronVoronov** [comment]
`
{
  "name": "tumbler",
  "version": "20.01.05",
  "description": "Tumbler System",
  "author": "Murashev D",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js",
    "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs",
    "gulp": "gulp"
  },
  "dependencies": {
    "-": "0.0.1",
    "@mdi/font": "^5.9.55",
    "@ssthouse/vue-tree-chart": "^0.6.7",
    "axios": "^0.21.1",
    "chart.js": "^2.9.4",
    "compression-webpack-plugin": "^8.0.1",
    "date-fns": "^2.27.0",
    "fs": "^0.0.1-security",
    "fusioncharts": "^3.15.1-sr.1",
    "gulp": "^4.0.2",
    "js-cookie": "^2.2.0",
    "lodash": "^4.17.21",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.18.1",
    "pug": "^3.0.2",
    "string-format-validation": "^2.0.2",
    "vue": "^2.6.10",
    "vue-axios": "^2.1.4",
    "vue-chartjs": "^3.4.0",
    "vue-chat-scroll": "^1.4.0",
    "vue-clipboards": "^1.2.4",
    "vue-document-editor": "^1.5.1",
    "vue-emoji-picker": "^1.0.1",
    "vue-fusioncharts": "^3.0.4",
    "vue-lodash": "^2.1.2",
    "vue-native-notification": "^1.0.5",
    "vue-phone-number-input": "^1.1.9",
    "vue-router": "^2.3.1",
    "vue-sweetalert2": "^1.6.4",
    "vue-the-mask": "^0.11.1",
    "vuetify": "^2.2.19",
    "vuetify-upload-button": "^2.0.2",
    "vuex": "^3.1.3",
    "vuex-persistedstate": "^2.7.1",
    "xlsx": "^0.17.0"
  },
  "devDependencies": {
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^4.0.0",
    "cross-spawn": "^5.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^3.19.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.19.1",
    "merge-stream": "^1.0.1",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "rimraf": "^2.6.0",
    "sass-loader": "^7.3.1",
    "selenium-server": "^3.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "smart-grid": "^1.1.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "url-loader": "^0.5.8",
    "vinyl-buffer": "^1.0.0",
    "vue-loader": "^12.2.2",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
`

**Comment by VoronVoronov** [comment]
[package.json](https://github.com/motla/vue-document-editor/files/13609286/package.json)
