### ISSUE TITLE
page break inside avoid not works

### ISSUE THREAD

**Issue by mentik** [motla/vue-document-editor#39]
Thank you, this project is really great.
Is there a way to make css `page-break-inside:avoid` works to the editor?

**Comment by motla** [comment]
Yes you can set the `:do-not-break` property on the global editor, to match elements with CSS `page-break-inside:avoid` (using [getComputedStyle()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle))

Docs: https://github.com/motla/vue-document-editor/blob/master/API.md#props

**Comment by mentik** [comment]
@motla thanks you very much ....
