### ISSUE TITLE
problem with ?. operator

### ISSUE THREAD

**Issue by Mishkoo93** [motla/vue-document-editor#4]
**Describe the bug**
After update depencies i have a bug when im try to run watch/dev/build

ERROR in ./node_modules/vue-document-editor/src/DocumentEditor/DocumentEditor.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-document-editor/src/DocumentEditor/DocumentEditor.vue?vue&type=script&lang=js&) 380:61
Module parse failed: Unexpected token (380:61)
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|         // add overlays if any
>         const overlay_elt = this.$refs[page.uuid+'-overlay']?.[0];
|         if(overlay_elt){

i'm using vuetifyjs-mix-extension loader, and eslint prettier
and i think my loader, or babel transplitter cant load "?." operator, when im delete this new code all going to be ok

**my .babelrc**
{
  "plugins": ["@babel/plugin-syntax-dynamic-import"]
}

**my eslint**
module.exports = {
  root: true,
  env: {
    es6: true,
  },
  parserOptions: {
    parser: '@babel/eslint-parser',
    sourceType: 'module',
    requireConfigFile: false,
  },
  plugins: ['prettier', 'vue'],
  extends: [
    'vuetify',
    'plugin:vue/recommended', // Use this if you are using Vue.js 2.x.
    'plugin:prettier/recommended',
    'prettier/vue',
    'prettier',
  ],
  rules: {
    'vue/max-attributes-per-line': 'off',
    'vue/no-use-v-if-with-v-for': 'warn',
    'vue/no-side-effects-in-computed-properties': 'warn',
    'vuetify/no-deprecated-classes': 'error',
    'object-shorthand': ['error', 'always'],
  },
}

**Desktop (please complete the following information):**
 - OS: Linux Mint

**Additional context**

**Comment by motla** [comment]
Thanks a lot for reporting this bug.
I added the overlay functionality recently and forgot that in case of an import via NPM, the library is compiled by the client.
I guess you just have to set
```json
"env": {
  "es2020": true
},
```
to your eslint configuration for it to work, but as it's non standard yet, I've rewritten it in the old school way and released patch [#v1.2.2](https://github.com/motla/vue-document-editor/releases/tag/v1.2.2).
It should work fine now.
