### ISSUE TITLE
style not found in template

### ISSUE THREAD

**Issue by itokia** [motla/vue-document-editor#41]
Good morning,
When I want to test vue-document-editor, the layout is not taken into account.
I copied the demo.vue file and InvoiceTemplate.ce.vue which I placed in my sources but all the css that is in InvoiceTemplate.ce.vue is not interpreted.
Do you have any idea of the reason?
THANKS

**Comment by motla** [comment]
Yes, you need to read this: https://vuejs.org/guide/extras/web-components.html#sfc-as-custom-element

The library uses `defineCustomElement` to instantiate the template.
It should come from your project dependencies:

> The official SFC toolings support importing SFCs in "custom element mode" (requires @vitejs/plugin-vue@^1.4.0 or vue-loader@^16.5.0).

**Comment by itokia** [comment]
Many thanks for the lead, I'll look there

Edit: I just had to rename my file with the extension ce.vue
