### ISSUE TITLE
Question transcribe your demo.vue page into <script setup>

### ISSUE THREAD

**Issue by itokia** [motla/vue-document-editor#42]
Hello,
I would like to transcribe your demo.vue page into <script setup> format. I block at the watcher level with this._mute_next_content_watcher. Can you tell me what this corresponds to? I did a search in your project and I can't find it anywhere else. If you wish, I could give you the source code for those who are interested.
Thank you

**Comment by motla** [comment]
Yes, the undo/redo example in the demo.vue file is actually very basic. It is implemented like this: whenever `content` is modified (when you edit text), all its content is stored in `content_history` array (see [`watch`](https://github.com/motla/vue-document-editor/blob/559089e01444a8d5a40e6bfe01eebacad4e2d6a8/src/Demo/Demo.vue#L365-L377)).
When you do an Undo action, the `content_history` array is browsed backwards and the `content` is reversed accordingly ([see `undo` and `redo` methods](https://github.com/motla/vue-document-editor/blob/559089e01444a8d5a40e6bfe01eebacad4e2d6a8/src/Demo/Demo.vue#L321-L322)).

However, the reverse action also modifies the `content`, so it triggers the `content` watcher, which would normally store the content in the `content_history` array again. To prevent this we set a flag (`_mute_next_content_watcher`) that we set in the undo() and redo() functions. If this flag is set, the `content` modification is ignored and not stored in `content_history`.

Note that `_mute_next_content_watcher` is only implicitly declared (it is `undefined` by default). If you use `<script setup>` you may have to declare it as a variable somewhere, like: `let mute_next_content_watcher = false`.
