### ISSUE TITLE
Icon appear as text even after installing dependency

### ISSUE THREAD

**Issue by nanarosley** [motla/vue-document-editor#43]
Icon appear as text even after installing dependency

I use this for so long, and it works perfectly well but somehow lately the icon did not appear and it appear as text. please help look into this matter and help me solve this. Thank you

![image](https://github.com/motla/vue-document-editor/assets/121274234/206a786c-8ce6-4370-b3b1-a120c885a565)

**Comment by motla** [comment]
This is more related to [vue-file-toolbar-menu](https://github.com/motla/vue-file-toolbar-menu).
With no code and just a screenshot I can't help you much...
Did you do `npm install vue-file-toolbar-menu` ?
