### ISSUE TITLE
Unable to update the document

### ISSUE THREAD

**Issue by nanarosley** [motla/vue-document-editor#44]
Hi, I did follow all the demo code you gave me, and I even add:

`watch: {
        content: {
            immediate: true,
            // Fill undo / redo history stack on user input
            handler (new_content) {
                if(!this._mute_next_content_watcher) { // only update the stack when content is changed by user input, not undo/redo commands
                this.content_history[++this.undo_count] = new_content;
                this.content_history.length = this.undo_count + 1; // remove all redo items
                }
                this._mute_next_content_watcher = false;
            }
        },
        }`
        
 But my content still not update whenever I edit something in the document. When I try to submit, it submit the unedited document instead of the updated ones, below here is my code reference:
 
 ` <cv-modal v-bind="props" :visible="createChecklistModal" :kind="kind" :size="size"
        :primaryButtonDisabled="primaryButtonDisabled_CF" :disableTeleport="disableTeleport_CF"
        @after-modal-hidden="onAfterModalHidden_CF" @modal-hidden="onModalHidden_CF"
        @modal-hide-request="onModalHideRequest_CF" @modal-shown="onModalShown_CF" @primary-click="onPrimaryClickClose"
        @secondary-click="onSecondaryClickDiscard" @other-btn-click="onOtherBtnClick_CF" id="checklistModal">

        <template v-slot:title>⚠️ Create template</template>
        <template v-slot:content>
            
            
            <vue-file-toolbar-menu :content="menu" class="bar" />

            
            <vue-document-editor id="textEditor" class="editor" ref="editor"
            v-model:content="content"
            :overlay="overlay"
            :zoom="zoom"
            :page_format_mm="page_format_mm"
            :page_margins="page_margins"
            :display="display"
            :contenteditable="edit_mode" spellcheck="false" />

            

        </template>
        <template v-slot:secondary-button>Back</template>
        <template v-slot:primary-button>Save</template>
    </cv-modal>`
    
    Script:
    
    `async onPrimaryClickTemplate() {
            console.log("CREATE TEMPLATE WAS CLICK")

            console.log(this.content);

            if (this.content.length === 0 || (this.content.length === 1 && this.content[0] === '')) {
                const endPoint = process.env.VUE_APP_END_POINT;

                const config = {
                    headers: {
                        Authorization: 'Bearer ' + this.currentUser.access_token,
                        'Content-Type': 'application/json', // Set Content-Type to application/json
                    },
                };

                try {
                    const response = await this.$axios.get(
                        endPoint + '/test/api/addApp/defaultTemplate',
                        config
                    );

                    const data = response.data.content;
                    console.log(response.data.content);
                    this.content = [data];

                    const currentDate = new Date();
                    // Extract day, month, and year
                    const day = currentDate.getDate().toString().padStart(2, '0');
                    const month = (currentDate.getMonth() + 1).toString().padStart(2, '0');
                    const year = currentDate.getFullYear();
                    const dayText = currentDate.getDate();
                    const monthText = new Intl.DateTimeFormat('en-US', { month: 'long' }).format(currentDate);
                    const yearText = currentDate.getFullYear();
                    const formattedDateText = `${dayText} ${monthText} ${yearText}`;
                    const formattedDate = `${day}/${month}/${year}`;
                    const roleTypeUpperCase = this.roleType.toUpperCase();
                } catch (error) {
                    console.error("Error fetching checklist data:", error);
                }
            }`

**Comment by motla** [comment]
Sorry it seems there is a lot of things not working in your project which you have to fix but it is probably not related with this library.
I would recommend coding little step by little step, starting from scratch, having a blank project which runs and add one element at a time, testing it before adding a new one and understand every line of your code (not just copying it from somewhere and hoping for it to work).
Also working with DevTools in your browser is very important. You have to fix the warnings and errors in the console, if any, and you may put breakpoints in your JavaScript code for it to stop at a given point and inspect the values of the variables and see how the code changes them.
However this effort has to come from you, I can only answer questions if you don't understand this library, or if you find a bug which you are absolutely sure it comes from the library and not from your application (which I can easily reproduce without installing any component or library other than Vue and this one).
Everyone goes through this, just persevere, understand and be patient, you will learn a lot but it's hard and takes time.
Good luck
