### ISSUE TITLE
Cabeçalhos e rodapés não funcionam

### ISSUE THREAD

**Issue by krefects** [motla/vue-document-editor#6]
O texto do cabeçalho sobrepou o texto, o editor não redimensiona automaticamente.
![print1](https://user-images.githubusercontent.com/17180773/113302253-40a2cd80-92d6-11eb-8ba5-62baf3eeded8.png)
![print2](https://user-images.githubusercontent.com/17180773/113302280-4698ae80-92d6-11eb-9c68-a110d0663109.png)

**Comment by motla** [comment]
Yes this is as expected.
You can set `page_margins` (see the [API](https://github.com/motla/vue-document-editor/blob/master/API.md)) to the correct value for your document for the overlay not to overlap with the contents of the page.
It can be "top right bottom left" format like "30mm 15mm 10mm 15mm".

**Comment by krefects** [comment]
Funcionou!
Obrigado!
