### ISSUE TITLE
Travamentos a partir de 10 páginas

### ISSUE THREAD

**Issue by krefects** [motla/vue-document-editor#8]
o editor começa a travar apartir de 10 páginas, não sendo possível continuar.
observei que a renderização de páginas acontece a cada letra digitada.

**Comment by motla** [comment]
Yes this is a known issue, as written in the readme. The algorithm for splitting the content in several pages runs every time you type a letter, and involves HTML DOM manipulation that is quite heavy as the number of pages grow.
So for now you can't use this library for big documents, the algorithm doesn't work well for big documents. Sorry
