### ISSUE TITLE
Using `editable` prop to provide read only view

### ISSUE THREAD

**Issue by eksha** [motla/vue-document-editor#9]
**Describe the bug**
I want to use the component to render the content  previously saved by the editor, in a non-editable/read only mode.
Component prop `editable` suggests `// Sets whether document text can be modified`.
But setting this prop as false, only sets the wrapper div (ref=content) as `contentEditable= false`
![image](https://user-images.githubusercontent.com/24860934/124333518-151fcf80-dbb2-11eb-89e2-532b30131602.png)
For subsequent pages in the loop the `contentEditable` property is decided on the fact if the page object has a template property or not, and since the property is not present (in general case of direct content saving), contentEditable property for page remains true, and it stays editable.
![image](https://user-images.githubusercontent.com/24860934/124333577-43051400-dbb2-11eb-9440-9df815831920.png)

Is it expected to behave this way? Is there any workaround to achieve the non-editable mode?

**To Reproduce**
1. Use `:editable="false"` prop in component

Code
```js
<vue-document-editor 
        class="editor"
        :editable="false"
                            :style="{
                                height:'80vh',
                                overflowY: 'scroll'
                            }"
                            ref="editor"
                            :content.sync="content"
                            :overlay="overlay"
                            :zoom="zoom"
                            :page_format_mm="page_format_mm"
                            :page_margins="page_margins"
                            :display="display"/>
```

**Expected behavior**
Setting editable prop to false should render the full document/all pages non-editable.

**Screenshots**
![image](https://user-images.githubusercontent.com/24860934/124333729-b9097b00-dbb2-11eb-93e1-6058976c04ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chromium

Thanks!

**Comment by motla** [comment]
Exact. Well done reporting this bug. [v1.2.5](releases/tag/v1.2.5) should fix it.
Let me know if you have any other question.

**Comment by eksha** [comment]
Thanks, works perfect!
